name: elementpath

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:

    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "pypy-3.8"]
        exclude:
          - os: macos-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2
      - name: Install additional development libraries for building lxml
        if: ${{ matrix.os == 'ubuntu-latest' && (matrix.python-version == '3.10' || matrix.python-version == 'pypy-3.8') }}
        run: sudo apt-get update && sudo apt-get install libxml2-dev libxslt-dev python-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 elementpath --max-line-length=100 --statistics
      - name: Lint with mypy if Python version != 3.7
        if: ${{ matrix.python-version != '3.7' }}
        run: |
          pip install mypy==0.950
          mypy --show-error-codes --strict elementpath
      - name: Lint with mypy if Python version == 3.7
        if: ${{ matrix.python-version == '3.7' }}
        run: |
          pip install mypy==0.950
          mypy --show-error-codes --no-warn-redundant-casts --no-warn-unused-ignores --strict elementpath
      - name: Test with unittest
        run: |
          pip install lxml xmlschema>=1.9.0
          python -m unittest
